# Generated by Django 3.0.8 on 2020-08-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
