# Generated by Django 3.0.8 on 2020-08-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_model_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
